### ISSUE TITLE
Error encountered

### ISSUE THREAD

**Issue by hemangjoshi37a** [matusnovak/HGS2561281#1]
Energia: 1.6.10E18 (Linux), Board: "MSP-EXP430G2553LP"

WARNING: Spurious .github folder in 'Adafruit ADS1X15' library
WARNING: Spurious .github folder in 'RTClib' library
<command-line>:0:12: warning: missing whitespace after the macro name [enabled by default]
<command-line>:0:12: warning: missing whitespace after the macro name [enabled by default]
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.cpp:19:0: warning: "pgm_read_byte" redefined [enabled by default]
/media/hemang/586E740B6E73DFE4/msp/energia/hardware/energia/msp430/cores/msp430/avr/pgmspace.h:30:0: note: this is the location of the previous definition
<command-line>:0:12: warning: missing whitespace after the macro name [enabled by default]
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In constructor 'Adafruit_SSD1306::Adafruit_SSD1306(int8_t, int8_t, int8_t, int8_t, int8_t)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:134:145: error: no matching function for call to 'Adafruit_GFX::Adafruit_GFX(int, int)'
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:134:145: note: candidates are:
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note: Adafruit_GFX::Adafruit_GFX()
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note:   candidate expects 0 arguments, 2 provided
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note: Adafruit_GFX::Adafruit_GFX(const Adafruit_GFX&)
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note:   candidate expects 1 argument, 2 provided
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In constructor 'Adafruit_SSD1306::Adafruit_SSD1306(int8_t, int8_t, int8_t)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:144:120: error: no matching function for call to 'Adafruit_GFX::Adafruit_GFX(int, int)'
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:144:120: note: candidates are:
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note: Adafruit_GFX::Adafruit_GFX()
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note:   candidate expects 0 arguments, 2 provided
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note: Adafruit_GFX::Adafruit_GFX(const Adafruit_GFX&)
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note:   candidate expects 1 argument, 2 provided
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In constructor 'Adafruit_SSD1306::Adafruit_SSD1306(int8_t)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:153:49: error: no matching function for call to 'Adafruit_GFX::Adafruit_GFX(int, int)'
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:153:49: note: candidates are:
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note: Adafruit_GFX::Adafruit_GFX()
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note:   candidate expects 0 arguments, 2 provided
Multiple libraries were found for "Adafruit_SSD1306.h"
 Used: /media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306
 Not used: /media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306_Energia-master
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note: Adafruit_GFX::Adafruit_GFX(const Adafruit_GFX&)
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit-GFX/Adafruit_GFX.h:28:7: note:   candidate expects 1 argument, 2 provided
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In member function 'void Adafruit_SSD1306::begin(uint8_t, uint8_t, bool)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:167:67: error: 'portBASERegister' was not declared in this scope
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In member function 'void Adafruit_SSD1306::ssd1306_command(uint8_t)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:340:50: error: 'ROM_GPIOPinWrite' was not declared in this scope
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In member function 'void Adafruit_SSD1306::ssd1306_data(uint8_t)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:454:50: error: 'ROM_GPIOPinWrite' was not declared in this scope
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In member function 'void Adafruit_SSD1306::display()':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:494:50: error: 'ROM_GPIOPinWrite' was not declared in this scope
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp: In member function 'void Adafruit_SSD1306::fastSPIwrite(uint8_t)':
/media/hemang/586E740B6E73DFE4/msp/energia/libraries/Adafruit_SSD1306/Adafruit_SSD1306.cpp:547:46: error: 'ROM_GPIOPinWrite' was not declared in this scope
exit status 1
Error compiling for board MSP-EXP430G2553LP.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by hemangjoshi37a** [comment]
Please help me solve  this  error.

**Comment by matusnovak** [comment]
@hemangjoshi37a Can you post the part of the code where you import the libraries?

**Comment by matusnovak** [comment]
@hemangjoshi37a I had another look into Energia and the errors you posted. Are you using the Adafruit_SSD1306 and Adafruit_GFX libraries? They are not related to my library HGS2561281. 

Some of the errors indicate that `ROM_GPIOPinWrite` and `portBASERegister` were not declared. I scanned through entire Energia 1.6.10 MSP430 folder and could not find anything declared as `ROM_GPIOPinWrite` nor `portBASERegister`. 

However, the both names I have mentioned can be found in `TivaC` board. I see that you are using `MSP-EXP430G2553LP`. Are you using the correct board? Maybe the adafruit libraries you are using are outdated or not available to MSP board.

The issue you have seems to be related to adafruit libraries and not to HGS2561281 library.
